import { Spell, SpellSchool, SpellTier, SpellType } from './spell.types';

// Значения по умолчанию из раздела 5.2 game-design.md (середина диапазона каждого уровня)
const TIER_DEFAULTS: Record<
  SpellTier,
  { cooldownMs: number; castWindowMs: number }
> = {
  [SpellTier.Basic]: { cooldownMs: 4000, castWindowMs: 1800 },
  [SpellTier.Advanced]: { cooldownMs: 12000, castWindowMs: 3000 },
  [SpellTier.Ultimate]: { cooldownMs: 30000, castWindowMs: 5000 },
};

function spell(
  id: string,
  name: string,
  trigger: string,
  school: SpellSchool,
  type: SpellType,
  tier: SpellTier,
  description: string,
): Spell {
  return {
    id,
    name,
    trigger,
    school,
    type,
    tier,
    description,
    ...TIER_DEFAULTS[tier],
  };
}

export const SPELL_ROSTER: Spell[] = [
  // Fire
  spell(
    'fire_spark',
    'Spark',
    'spark',
    SpellSchool.Fire,
    SpellType.Attack,
    SpellTier.Basic,
    'Небольшая искра, малый прямой урон',
  ),
  spell(
    'fire_ember_ward',
    'Ember Ward',
    'guard',
    SpellSchool.Fire,
    SpellType.Defense,
    SpellTier.Basic,
    'Огненная плёнка, снижает входящий урон',
  ),
  spell(
    'fire_blaze',
    'Blaze',
    'inferno',
    SpellSchool.Fire,
    SpellType.Attack,
    SpellTier.Advanced,
    'Вспышка пламени + поджог (DoT 3 сек)',
  ),
  spell(
    'fire_phoenix_rebirth',
    'Phoenix Rebirth',
    'phoenixrise',
    SpellSchool.Fire,
    SpellType.Support,
    SpellTier.Ultimate,
    'Исцеление + временный щит от смертельного удара',
  ),
  spell(
    'fire_inferno_storm',
    'Inferno Storm',
    'firestormrage',
    SpellSchool.Fire,
    SpellType.Attack,
    SpellTier.Ultimate,
    'Мощный взрыв, максимальный прямой урон школы',
  ),

  // Ice
  spell(
    'ice_frostbite',
    'Frostbite',
    'frost',
    SpellSchool.Ice,
    SpellType.Attack,
    SpellTier.Basic,
    'Малый урон + лёгкое замедление ввода соперника',
  ),
  spell(
    'ice_winters_grasp',
    "Winter's Grasp",
    'chill',
    SpellSchool.Ice,
    SpellType.Support,
    SpellTier.Basic,
    'Замедляет восстановление кулдауна соперника',
  ),
  spell(
    'ice_ice_shard',
    'Ice Shard',
    'iceshard',
    SpellSchool.Ice,
    SpellType.Attack,
    SpellTier.Advanced,
    'Средний урон, шанс скрыть подсказку ввода на 1 сек',
  ),
  spell(
    'ice_frozen_armor',
    'Frozen Armor',
    'glacierwall',
    SpellSchool.Ice,
    SpellType.Defense,
    SpellTier.Advanced,
    'Ледяной щит: поглощение + лёгкое отражение',
  ),
  spell(
    'ice_blizzard',
    'Blizzard',
    'absolutezero',
    SpellSchool.Ice,
    SpellType.Attack,
    SpellTier.Ultimate,
    'Нарастающий урон + сильное замедление',
  ),

  // Arcane
  spell(
    'arcane_mana_bolt',
    'Mana Bolt',
    'pulse',
    SpellSchool.Arcane,
    SpellType.Attack,
    SpellTier.Basic,
    'Стабильный урон без побочных эффектов',
  ),
  spell(
    'arcane_silence',
    'Silence',
    'mute',
    SpellSchool.Arcane,
    SpellType.Support,
    SpellTier.Basic,
    'Блокирует один слот заклинания соперника',
  ),
  spell(
    'arcane_arcane_missile',
    'Arcane Missile',
    'starfall',
    SpellSchool.Arcane,
    SpellType.Attack,
    SpellTier.Advanced,
    'Урон, игнорирующий часть защиты',
  ),
  spell(
    'arcane_mirror_shield',
    'Mirror Shield',
    'reflectio',
    SpellSchool.Arcane,
    SpellType.Defense,
    SpellTier.Advanced,
    'Отражает часть входящего урона',
  ),
  spell(
    'arcane_time_warp',
    'Time Warp',
    'chronoshift',
    SpellSchool.Arcane,
    SpellType.Support,
    SpellTier.Ultimate,
    'Сбрасывает кулдаун одного своего заклинания',
  ),

  // Chaos
  spell(
    'chaos_chaos_bolt',
    'Chaos Bolt',
    'chaos',
    SpellSchool.Chaos,
    SpellType.Attack,
    SpellTier.Basic,
    'Урон варьируется в широком диапазоне',
  ),
  spell(
    'chaos_unstable_surge',
    'Unstable Surge',
    'wildmagic',
    SpellSchool.Chaos,
    SpellType.Support,
    SpellTier.Advanced,
    'Случайный бафф (крит / скорость / щит)',
  ),
  spell(
    'chaos_chaotic_shield',
    'Chaotic Shield',
    'entropyveil',
    SpellSchool.Chaos,
    SpellType.Defense,
    SpellTier.Advanced,
    'Случайно полный блок ИЛИ отражение',
  ),
  spell(
    'chaos_corruption',
    'Corruption',
    'plaguebind',
    SpellSchool.Chaos,
    SpellType.Attack,
    SpellTier.Advanced,
    'Урон + случайная длительность DoT',
  ),
  spell(
    'chaos_void_collapse',
    'Void Collapse',
    'oblivionrift',
    SpellSchool.Chaos,
    SpellType.Attack,
    SpellTier.Ultimate,
    'Огромный урон, но откатывает свой следующий кулдаун',
  ),

  // Nature
  spell(
    'nature_vine_whip',
    'Vine Whip',
    'vine',
    SpellSchool.Nature,
    SpellType.Attack,
    SpellTier.Basic,
    'Малый урон + короткий рут соперника',
  ),
  spell(
    'nature_bark_skin',
    'Bark Skin',
    'barkskin',
    SpellSchool.Nature,
    SpellType.Defense,
    SpellTier.Basic,
    'Пассивное снижение урона на время действия',
  ),
  spell(
    'nature_entangle',
    'Entangle',
    'rootbind',
    SpellSchool.Nature,
    SpellType.Support,
    SpellTier.Advanced,
    'Сильное замедление без урона',
  ),
  spell(
    'nature_regrowth',
    'Regrowth',
    'lifebloom',
    SpellSchool.Nature,
    SpellType.Support,
    SpellTier.Advanced,
    'Лечение за 2 тика',
  ),
  spell(
    'nature_natures_fury',
    "Nature's Fury",
    'wildgrowthrage',
    SpellSchool.Nature,
    SpellType.Attack,
    SpellTier.Ultimate,
    'Крупный урон + шанс доп. рута',
  ),
];
